### ISSUE TITLE
Detected a problem that could interfere with the system login proccess

### ISSUE THREAD

**Issue by 3ab3z2** [mshernandez5/WelcomeXP#19]
Hi, I'm using Debian 12 with xfce and I installed nody-greeter, it worked the first time I installed it with its default theme, but once I installed the WelcomeXP theme I can't login anymore, the greeter shows and the theme is perfect, but when I enter the password nothing happens.
when I run 
```
nody-greeter --debug
``` 
I get this message: 

![image](https://github.com/mshernandez5/WelcomeXP/assets/126415531/7d8cbce9-ffca-48c9-8b08-2f549cc9ba41)

and 
```
[3592:0220/194802.834737:ERROR:node_bindings.cc(242)] Error parsing Node.js cli flags 
2024-02-20 19:48:02 [ WARN ] config.js 224: Theme config was not loaded:
	Error: ENOENT: no such file or directory, open '/usr/share/web-greeter/themes/WelcomeXP/index.yml'
2024-02-20 19:48:02 [ DEBUG ] config.js 225: Using default theme config
2024-02-20 19:48:03 [ ERROR ] acpi.js 36: ACPI: acpi_listen does not exists
2024-02-20 19:48:03 [ DEBUG ] browser.js 125: Initializing Browser Window
2024-02-20 19:48:03 [ DEBUG ] browser.js 177: Browser Window created
2024-02-20 19:48:03 [ DEBUG ] screensaver.js 42: Screensaver set
2024-02-20 19:48:03 [ DEBUG ] browser.js 122: Theme loaded
2024-02-20 19:48:03 [ DEBUG ] globals.js 16: Javascript logger is ready
2024-02-20 19:48:03 [ DEBUG ] globals.js 13: Window is ready
2024-02-20 19:48:03 [ ERROR ] bridge.js 53: Error: Unable to determine socket to daemon
    at new Greeter (/opt/nody-greeter/resources/app.asar/js/bridge/bridge.js:49:28)
    at Function.getInstance (/opt/nody-greeter/resources/app.asar/js/bridge/bridge.js:99:52)
    at /opt/nody-greeter/resources/app.asar/js/bridge/bridge.js:718:37
[3592:0220/194803.176791:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_ensure_shared_data_dir_sync: assertion 'priv->connected' failed
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
2024-02-20 19:48:03 [ DEBUG ] bridge.js 70: LightDM API connected
[3624:0220/194803.179019:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
2024-02-20 20:16:12 [ DEBUG ] browser.js 198: Nody Greeter started win: 2785062953156674
[3592:0220/201614.338715:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_authenticate: assertion 'priv->connected' failed
[3592:0220/201620.075528:ERROR:browser_main_loop.cc(269)] <unknown>: lightdm_greeter_respond: assertion 'priv->connected' failed
2024-02-20 20:16:26 [ DEBUG ] screensaver.js 58: Screensaver reset
```

**Comment by mshernandez5** [comment]
Hello! I just installed Debian 12 /w XFCE in a VM to try things out and was able to get things working fine following the README steps with minor changes (now using nody-greeter 1.5.2, NodeJS v18.x, and `liblightdm-gobject-1-dev` -> `liblightdm-gobject-dev` for Debian)

```
2024-02-20 19:48:02 [ WARN ] config.js 224: Theme config was not loaded:
	Error: ENOENT: no such file or directory, open '/usr/share/web-greeter/themes/WelcomeXP/index.yml'
```
This is unusual and I am curious to see what `ls -l /usr/share/web-greeter/themes/WelcomeXP` and `ls -l /usr/share/web-greeter/themes` look like. Files might be missing from that directory or the permissions may be off.

Also, I do not believe this is related to your issue but do make sure to specify `user-session=xfce` in `/etc/lightdm/lightdm.conf` since this theme relies on a configured default rather than checking which ones are available.

**Comment by 3ab3z2** [comment]
```
-----> ls -l /usr/share/web-greeter/themes/WelcomeXP
total 36
drwxr-xr-x 2 root root 4096 Feb 20 19:05 css
drwxr-xr-x 2 root root 4096 Feb 20 19:05 img
-rwxr-xr-x 1 root root 5900 Feb 20 19:05 index.html
-rwxr-xr-x 1 root root  108 Feb 20 19:19 index.theme
drwxr-xr-x 2 root root 4096 Feb 20 19:05 js
-rwxr-xr-x 1 root root 4736 Feb 20 19:05 README.md
drwxr-xr-x 2 root root 4096 Feb 20 19:05 screenshot
```
```
----->ls -l /usr/share/web-greeter/themes
total 16
drwxr-xr-x 6 root root 4096 Feb 20 18:57 dracula
drwxr-xr-x 6 root root 4096 Feb 20 18:57 gruvbox
drwxr-xr-x 2 root root 4096 Feb 20 18:57 simple
drwxr-xr-x 6 root root 4096 Feb 20 19:19 WelcomeXP
```

I checked for the ``` user-session=xfce ``` and it's there.

also nody-greeter works just fine, it just doesn't login while using this theme, other themes work fine.

**Comment by mshernandez5** [comment]
What version of WelcomeXP are you using? Based on the file sizes and missing `index.yml` it looks like this is a very old version.

Try removing this installation by doing `sudo rm -rf /usr/share/web-greeter/themes/WelcomeXP` then reinstall /w steps 4-7 in the "WelcomeXP Installation" section of the README. Note that the README says `git checkout v0.4.1` which is fine but you can skip this step since `master` branch is good right now I just haven't made a new release tag yet. Then again check with `nody-greeter --debug` to make sure the greeter starts up before logging out.

Hopefully this works.

**Comment by 3ab3z2** [comment]
I was using the latest version, I removed the installation and did it again according to the README but still the same issue appeared.

**Comment by mshernandez5** [comment]
1. Just to check what do `ls -l /usr/share/web-greeter/themes/WelcomeXP` and `ls -l /usr/share/web-greeter/themes` look like now?
2. Do you have the same issue with the `simple` theme? (in `/etc/lightdm/web-greeter.yml` set `theme: simple`) I ask because it is the only other default theme which relies on the default session being set correctly.

**Comment by 3ab3z2** [comment]
```
--->ls -l /usr/share/web-greeter/themes/WelcomeXP
total 44
drwxr-xr-x 2 root root 4096 Feb 22 22:37 css
drwxr-xr-x 2 root root 4096 Feb 22 22:37 img
-rwxr-xr-x 1 root root 6104 Feb 22 22:43 index.html
-rwxr-xr-x 1 root root   59 Feb 22 22:43 index.yml
drwxr-xr-x 2 root root 4096 Feb 22 22:37 js
-rwxr-xr-x 1 root root 8441 Feb 22 22:43 README.md
drwxr-xr-x 2 root root 4096 Feb 22 22:37 screenshot
-rwxr-xr-x 1 root root  880 Feb 22 22:43 secondary.html
```

```
--->ls -l /usr/share/web-greeter/themes
total 16
drwxr-xr-x 6 root root 4096 Feb 20 18:57 dracula
drwxr-xr-x 6 root root 4096 Feb 20 18:57 gruvbox
drwxr-xr-x 2 root root 4096 Feb 20 18:57 simple
drwxr-xr-x 7 root root 4096 Feb 22 22:37 WelcomeXP
```

And yes, the same issue happens with ```simple``` theme, I think the problem is with nody-greeter?

Edit: it was the fault of nody-greeter, I reinstalled it and everything works perfectly now.
